#使用本地代理
prefix: "http://127.0.0.1:"
proxy: "7897"
#根据本地代理修改: "http://127.0.0.1:xxxxx"   xxxx为你代理使用的端口
cookie: xxxxxxxxxxxxxx

#是否启用代理
agelimit: true
#下载位置(相对)
downloadposition: Download

# 收藏数限制 ,低于的不下载
likelimit: 2000

# ms(毫秒) & > 1000(After revision)
retry429: 10000

# ms(毫秒) & > 200(After revision)
downloadinterval: 1000

# ms(毫秒) & > 200(After revision)
retryinterval: 3000

# 下载是否以作者id单独区分
differauthor: false
# 缓存超时时间(天)
expiredtime: 7
useproxy: true
